Cleanup of build scripts, make them more robust

diff --git a/scripts/build_maps b/scripts/build_maps
--- a/scripts/build_maps
+++ b/scripts/build_maps
@@ -3,72 +3,32 @@
 COUNTRY=${1:-DACH}
 SPLITTER_MAXNODES=1400000
 #SPLITTER_MAXNODES=700000
-SPLITTER_OVERLAP="0 --keep-complete=true"
-SPLITTER_OVERLAP_OLD=10000
-
-# URL COUNTRY SUFFIX
-DownloadSource()
-{
-  local UPDATE=0
-  local URL=$1
-  local OSMDATA=$2.$3
-
-  if [ x"$URL" != x -a ! -f no-download ]; then
-    mkdir -p data/osm
-    cd data/osm
-    if [ -f $OSMDATA ]; then
-      UPDATE=`echo $(((($(date +%s)-$(stat -c %Y ${OSMDATA})))/86400))`
-    else
-      UPDATE=1;
-    fi
-    if [ $UPDATE -ne 0 ]; then
-      test -f $OSMDATA && mv -f $OSMDATA $OSMDATA.tmp
-      wget -nv ${URL}${OSMDATA}
-      if [ $? -ne 0 ]; then
-         echo "wget failed!"
-         test -f $OSMDATA.tmp && mv -f  $OSMDATA.tmp $OSMDATA
-         exit 1
-      fi
-      test -f $OSMDATA.tmp && rm -f $OSMDATA.tmp
-    fi
-    cd ../..
-  fi
-}
+SPLITTER_OVERLAP=0
+RETVAL=0
 
 # Split country osm data into tiles
 SplitIntoTiles()
 {
-SRCDIR=$1
-OUTPUTDIR=build/$COUNTRY/$2
+    SRCDIR=$1
+    OUTPUTDIR=build/"$COUNTRY"/$2
 
-rm -rf $OUTPUTDIR
-mkdir -p $OUTPUTDIR
-if [ -f tk-osm/basemap/areas.$COUNTRY.list -a "$OUTPUTDIR" == "tiles" ]; then
+    rm -rf "$OUTPUTDIR"
+    mkdir -p "$OUTPUTDIR"
+    if [ -f tk-osm/basemap/areas."$COUNTRY".list -a "$OUTPUTDIR" == "tiles" ]; then
 	AREALIST="--split-file=tk-osm/basemap/areas.$COUNTRY.list"
-fi
+    fi
 
-PRECOMP_SEA=""
-if [ -e data/sea/current ]; then
-  PRECOMP_SEA="--precomp-sea=data/sea/current"
-fi
+    PRECOMP_SEA=""
+    if [ -e data/sea/current ]; then
+	PRECOMP_SEA="--precomp-sea=data/sea/current"
+    fi
 
-#case "$COUNTRY" in
-#  *)
-#  NOTRIM="--no-trim"
-#  ;;
-#esac
-#wget http://download.geonames.org/export/dump/cities15000.zip
-tilesplitter --mapid=$TILEID --max-nodes=${SPLITTER_MAXNODES} --overlap=${SPLITTER_OVERLAP} --max-areas=1024 $NOTRIM $PRECOMP_SEA --geonames-file=tk-osm/scripts/cities/${COUNTRY_ABBR}.txt  --description="$DESC" --output=pbf --output-dir=$OUTPUTDIR $SRCDIR/$COUNTRY.$SUFFIX $AREALIST
-RETVAL=$?
-#if [ $RETVAL -eq 255 ] ; then
-#   tilesplitter --mapid=$TILEID --max-nodes=${SPLITTER_MAXNODES} --overlap=${SPLITTER_OVERLAP_OLD} --max-areas=1024  $NOTRIM $PRECOMP_SEA --geonames-file=tk-osm/scripts/cities/${COUNTRY_ABBR}.txt  --description="$DESC" --output=pbf --output-dir=$OUTPUTDIR $SRCDIR/$COUNTRY.$SUFFIX $AREALIST
-#   RETVAL=$?
-#fi
-if [ $RETVAL -ne 0 -o ! -f $OUTPUTDIR/${TILEID}.osm.pbf ] ; then
-  echo "tilesplitter failed!"
-  exit 1
-fi
-test -f $SRCDIR/timestamp.txt && cp -v $SRCDIR/timestamp.txt $OUTPUTDIR
+    tilesplitter --mapid="$TILEID" --max-nodes=${SPLITTER_MAXNODES} --overlap=${SPLITTER_OVERLAP} --keep-complete=true --max-areas=1024 $PRECOMP_SEA --geonames-file=tk-osm/scripts/cities/${COUNTRY_ABBR}.txt  --description="$DESC" --output=pbf --output-dir="$OUTPUTDIR" "$SRCDIR/$COUNTRY.$SUFFIX" $AREALIST
+    if [ $? -ne 0 -o ! -f "$OUTPUTDIR/${TILEID}.osm.pbf" ] ; then
+	echo "tilesplitter failed!"
+	exit 1
+    fi
+    test -f "$SRCDIR/timestamp.txt" && cp -v "$SRCDIR/timestamp.txt" "$OUTPUTDIR"
 }
 
 SUFFIX="osm.pbf"
@@ -174,210 +134,198 @@ SRTM-*)
   esac
   ;;
 DACH)
-  MAPS="basemap basemap-noPOI bicycling oepnv wanderwege" # marine keepright address fixme
-  TILEID=71200001
-  COUNTRY_ABBR="DACH"
-  ;;
+    MAPS="basemap basemap-noPOI bicycling oepnv wanderwege" # marine keepright address fixme
+    TILEID=71200001
+    COUNTRY_ABBR="DACH"
+    ;;
 germany)
-  MAPS="basemap" # mkgmap
-  TILEID=71690001
-  COUNTRY_ABBR="DEU"
-  ;;
+    MAPS="basemap" # mkgmap
+    TILEID=71690001
+    COUNTRY_ABBR="DEU"
+    ;;
 europe)
-  MAPS="basemap bicycling oepnv wanderwege" # marine streets keepright fixme
-  TILEID=71100001
-  COUNTRY_ABBR="EU"
-  #SPLITTER_MAXNODES=1200000
-  ;;
+    MAPS="basemap bicycling oepnv wanderwege" # marine streets keepright fixme
+    TILEID=71100001
+    COUNTRY_ABBR="EU"
+    #SPLITTER_MAXNODES=1200000
+    ;;
 benelux)
-  MAPS="basemap bicycling oepnv wanderwege" # marine keepright fixme
-  TILEID=71700001
-  COUNTRY_ABBR="BNL"
-  ;;
+    MAPS="basemap bicycling oepnv wanderwege" # marine keepright fixme
+    TILEID=71700001
+    COUNTRY_ABBR="BNL"
+    ;;
 channel_islands)
-  MAPS="basemap bicycling oepnv" # wanderwege keepright marine fixme
-  TILEID=72200001
-  COUNTRY_ABBR="GBR"
-  ;;
+    MAPS="basemap bicycling oepnv" # wanderwege keepright marine fixme
+    TILEID=72200001
+    COUNTRY_ABBR="GBR"
+    ;;
 croatia)
-  MAPS="basemap bicycling oepnv wanderwege" # marine keepright marine fixme
-  TILEID=72300001
-  COUNTRY_ABBR="HRV"
-  ;;
+    MAPS="basemap bicycling oepnv wanderwege" # marine keepright marine fixme
+    TILEID=72300001
+    COUNTRY_ABBR="HRV"
+    ;;
 czech_republic)
-  MAPS="basemap bicycling oepnv wanderwege" # marine keepright fixme
-  TILEID=71300001
-  COUNTRY_ABBR="CZE"
-  ;;
+    MAPS="basemap bicycling oepnv wanderwege" # marine keepright fixme
+    TILEID=71300001
+    COUNTRY_ABBR="CZE"
+    ;;
 ireland)
-  MAPS="basemap bicycling oepnv wanderwege" # marine keepright fixme
-  TILEID=71340001
-  COUNTRY_ABBR="IRL"
-  ;;
+    MAPS="basemap bicycling oepnv wanderwege" # marine keepright fixme
+    TILEID=71340001
+    COUNTRY_ABBR="IRL"
+    ;;
 france)
-  MAPS="basemap bicycling oepnv wanderwege" # marine keepright fixme
-  TILEID=71600001
-  COUNTRY_ABBR="FRA"
-  ;;
+    MAPS="basemap bicycling oepnv wanderwege" # marine keepright fixme
+    TILEID=71600001
+    COUNTRY_ABBR="FRA"
+    ;;
 great_britain)
-  MAPS="basemap bicycling oepnv wanderwege" # keepright marine fixme
-  TILEID=72000001
-  COUNTRY_ABBR="GBR"
-  ;;
+    MAPS="basemap bicycling oepnv wanderwege" # keepright marine fixme
+    TILEID=72000001
+    COUNTRY_ABBR="GBR"
+    ;;
 iceland)
-  MAPS="basemap wanderwege oepnv bicycling" # marine keepright fixme
-  TILEID=72550001
-  COUNTRY_ABBR="ISL"
-  ;;
+    MAPS="basemap wanderwege oepnv bicycling" # marine keepright fixme
+    TILEID=72550001
+    COUNTRY_ABBR="ISL"
+    ;;
 india)
-  MAPS="basemap" # bicycling oepnv marine wanderwege keepright fixme
-  TILEID=72100001
-  COUNTRY_ABBR="IND"
-  ;;
+    MAPS="basemap" # bicycling oepnv marine wanderwege keepright fixme
+    TILEID=72100001
+    COUNTRY_ABBR="IND"
+    ;;
 italy)
-  MAPS="basemap bicycling oepnv wanderwege" # marine keepright fixme
-  TILEID=71800001
-  COUNTRY_ABBR="ITA"
-  ;;
+    MAPS="basemap bicycling oepnv wanderwege" # marine keepright fixme
+    TILEID=71800001
+    COUNTRY_ABBR="ITA"
+    ;;
 canada)
-  MAPS="basemap wanderwege" # bicycling oepnv marine keepright fixme
-  TILEID=71400001
-  COUNTRY_ABBR="CAN"
-  SPLITTER_MAXNODES=1200000
-  ;;
+    MAPS="basemap wanderwege" # bicycling oepnv marine keepright fixme
+    TILEID=71400001
+    COUNTRY_ABBR="CAN"
+    SPLITTER_MAXNODES=1200000
+    ;;
 usa*)
-  MAPS="basemap" # oepnv wanderwege bicycling marine keepright fixme
-  COUNTRY_ABBR="USA"
-  case "$COUNTRY" in
-    usa-northeast)
-      TILEID=71500001
-      ;;
-    usa-west)
-      TILEID=71500501
-      ;;
-    usa-midwest)
-      TILEID=71501001
-      ;;
-    usa-south)
-      TILEID=71501501
-      ;;
-    usa-caribbean)
-      TILEID=71520001
-      ;;
-  esac
-  ;;
+    MAPS="basemap" # oepnv wanderwege bicycling marine keepright fixme
+    COUNTRY_ABBR="USA"
+    case "$COUNTRY" in
+	usa-northeast)
+	    TILEID=71500001
+	    ;;
+	usa-west)
+	    TILEID=71500501
+	    ;;
+	usa-midwest)
+	    TILEID=71501001
+	    ;;
+	usa-south)
+	    TILEID=71501501
+	    ;;
+	usa-caribbean)
+	    TILEID=71520001
+	    ;;
+    esac
+    ;;
 portugal)
-  MAPS="basemap bicycling oepnv wanderwege" # marine
-  TILEID=72500001
-  COUNTRY_ABBR="PRT"
-  ;;
+    MAPS="basemap bicycling oepnv wanderwege" # marine
+    TILEID=72500001
+    COUNTRY_ABBR="PRT"
+    ;;
 scandinavia)
-  MAPS="basemap bicycling oepnv wanderwege" # marine keepright fixme
-  TILEID=71900001
-  COUNTRY_ABBR="DNS"
-  ;;
+    MAPS="basemap bicycling oepnv wanderwege" # marine keepright fixme
+    TILEID=71900001
+    COUNTRY_ABBR="DNS"
+    ;;
 spain)
-  MAPS="basemap bicycling oepnv wanderwege" # marine
-  TILEID=72400001
-  COUNTRY_ABBR="ESP"
-  ;;
+    MAPS="basemap bicycling oepnv wanderwege" # marine
+    TILEID=72400001
+    COUNTRY_ABBR="ESP"
+    ;;
 canary_islands)
-  MAPS="basemap bicycling oepnv wanderwege" # marine
-  TILEID=72400201
-  COUNTRY_ABBR="ESP"
-  ;;
+    MAPS="basemap bicycling oepnv wanderwege" # marine
+    TILEID=72400201
+    COUNTRY_ABBR="ESP"
+    ;;
 new_zealand)
-  MAPS="basemap wanderwege" # bicycling oepnv marine
-  TILEID=72600001
-  COUNTRY_ABBR="NZL"
-  ;;
+    MAPS="basemap wanderwege" # bicycling oepnv marine
+    TILEID=72600001
+    COUNTRY_ABBR="NZL"
+    ;;
 monaco)
-  MAPS="basemap" # bicycling oepnv wanderwege marine
-  TILEID=72680001
-  COUNTRY_ABBR="MCO"
-  ;;
+    MAPS="basemap" # bicycling oepnv wanderwege marine
+    TILEID=72680001
+    COUNTRY_ABBR="MCO"
+    ;;
 singapore)
-  MAPS="basemap" # bicycling oepnv wanderwege marine
-  TILEID=72660001
-  COUNTRY_ABBR="SGP"
-  ;;
+    MAPS="basemap" # bicycling oepnv wanderwege marine
+    TILEID=72660001
+    COUNTRY_ABBR="SGP"
+    ;;
 *)
-  echo "Country unknown!"
-  exit 1
-  ;;
+    echo "Country unknown!"
+    exit 1
+    ;;
 esac
 
-CAPCOUNTRY=`echo $COUNTRY | sed -e 's/^us-/US_/' -e 's/^usa-/USA_/' -e 's/^usa/USA/' | sed -e 's/\(.\)\(.*\)/\u\1\2/' | sed -e 's/\(.*\)_\(.\)\(.*\)/\1_\u\2\3/'`
 DESC="TK-${CAPCOUNTRY}-Tile"
 
 BASE_IS_SPLITTED=NO
 KEEPRIGHT_IS_SPLITTED=NO
 OSMBUGS_IS_SPLITTED=NO
-MARINE_IS_SPLITTED=NO
-LAYER_IS_SPLITTED=NO
 
 for style in $MAPS ; do
-  CAPSTYLE=`echo $style | sed -e 's/\(.\)\(.*\)/\u\1\2/'`
+    case "$style" in
+	srtm)
+	    SplitIntoTiles data/srtm tiles-srtm
+	    ;;
+	osb)
+	    if [ "$OSMBUGS_IS_SPLITTED" == "NO" ] ; then
+		/usr/bin/time tk-osm/scripts/update_osmbugs
+		if [ $? -ne 0 ] ; then
+		    echo "update_osmbugs for $COUNTRY failed!"
+		else
+		    SplitIntoTiles data/osmbugs tiles-osmbugs
+		    OSMBUGS_IS_SPLITTED=YES
+		fi
+	    fi
+	    ;;
+	keepright)
+	    if [ "$KEEPRIGHT_IS_SPLITTED" == "NO" ] ; then
+		/usr/bin/time tk-osm/scripts/update_keepright
+		if [ $? -eq 1 ] ; then
+		    echo "update_keepright for $COUNTRY failed!"
+		else
+		    TMPMAXNODES=$SPLITTER_MAXNODES
+		    SPLITTER_MAXNODES=20000
+		    SplitIntoTiles data/keepright tiles-keepright
+		    SPLITTER_MAXNODES=$TMPMAXNODES
+		    KEEPRIGHT_IS_SPLITTED=YES
+		fi
+	    fi
+	    ;;
+	*)
+	    if [ "$BASE_IS_SPLITTED" == "NO" ] ; then
+		SplitIntoTiles data/osm tiles
+		BASE_IS_SPLITTED=YES
+	    fi
+	    ;;
+    esac
+    echo "Building $style ..."
+    rm -rf "build/$COUNTRY/$style"
 
-  case "$style" in
-  srtm)
-    SplitIntoTiles data/srtm tiles-srtm
-    ;;
-  osb)
-    CAPSTYLE="OSB"
-    if [ "$OSMBUGS_IS_SPLITTED" == "NO" ] ; then
-      /usr/bin/time tk-osm/scripts/update_osmbugs
-      if [ $? -ne 0 ] ; then
-        echo "update_osmbugs for $COUNTRY failed!"
-      else
-        SplitIntoTiles data/osmbugs tiles-osmbugs
-        OSMBUGS_IS_SPLITTED=YES
-      fi
+    /usr/bin/time tk-osm/scripts/create_map "$style" "$COUNTRY" "$COUNTRY_ABBR"
+    if [ $? -ne 0 ] ; then
+	echo "create_map for $style failed!"
+	RETVAL=1
+	continue
     fi
-    ;;
-  keepright)
-    CAPSTYLE="KeepRight"
-    if [ "$KEEPRIGHT_IS_SPLITTED" == "NO" ] ; then
-      /usr/bin/time tk-osm/scripts/update_keepright
-      if [ $? -eq 1 ] ; then
-        echo "update_keepright for $COUNTRY failed!"
-      else 
-        TMPMAXNODES=$SPLITTER_MAXNODES
-        SPLITTER_MAXNODES=20000
-        SplitIntoTiles data/keepright tiles-keepright
-        SPLITTER_MAXNODES=$TMPMAXNODES
-        KEEPRIGHT_IS_SPLITTED=YES
-      fi
-    fi
-    ;;
-  #bicycling|hiking|oepnv|wanderwege|marine)
-  #  if [ "$LAYER_IS_SPLITTED" == "NO" ] ; then
-  #    TMPMAXNODES=$SPLITTER_MAXNODES
-  #    SPLITTER_MAXNODES=6000000
-  #    SplitIntoTiles data/osm tiles-layer
-  #    SPLITTER_MAXNODES=$TMPMAXNODES
-  #    LAYER_IS_SPLITTED=YES
-  #  fi
-  #  ;;
-  *)
-    if [ "$BASE_IS_SPLITTED" == "NO" ] ; then
-      SplitIntoTiles data/osm tiles
-      BASE_IS_SPLITTED=YES
-    fi
-    ;;
-  esac
-  echo "Building $style ..."
-  rm -rf build/$COUNTRY/$style
 
-  /usr/bin/time tk-osm/scripts/create_map $style $COUNTRY $COUNTRY_ABBR
-  if [ $? -ne 0 ] ; then
-    echo "create_map for $style failed!"
-    exit 1
-  fi
-
-  /usr/bin/time tk-osm/scripts/create_7z $style $COUNTRY
-  if [ $? -ne 0 ] ; then
-    echo "create_7z for $style failed!"
-    exit 1
-  fi
+    /usr/bin/time tk-osm/scripts/create_7z "$style" "$COUNTRY"
+    if [ $? -ne 0 ] ; then
+	echo "create_7z for $style failed!"
+	RETVAL=1
+	continue
+    fi
 done
+
+exit $RETVAL
