extract countries: replace osmconvert with osmium

diff --git a/scripts/extract_countries b/scripts/extract_countries
--- a/scripts/extract_countries
+++ b/scripts/extract_countries
@@ -26,19 +26,6 @@ print_date()
   date +"%F %k:%M"
 }
 
-extract()
-{
-# Arguments:
-# $1 - Input file
-# $2 - name of country
-  echo "Extracting $2 ..."
-  osmconvert $1 -B=tk-osm/scripts/poly/$2.poly --drop-author --drop-version --drop-broken-refs --out-pbf -o=${DATADIR}/.tmp/$2.osm.pbf
-  if [ $? -ne 0 ] ; then
-    echo "osmconvert failed extracting $2"
-    cleanup 2
-  fi
-}
-
 # check timestamp.txt content if we have a newer input file
 cmp -s "${INPUTDIR}/timestamp.txt" "${DATADIR}/timestamp.txt"
 if [ $? -eq 0 ] ; then
@@ -46,46 +33,53 @@ if [ $? -eq 0 ] ; then
   exit 1
 fi
 
-INPUT=$(/bin/ls ${INPUTDIR}/*-*.osm.* | sort -r | head -1)
+INPUT=$(/bin/ls "${INPUTDIR}"/planet-*.osm.pbf | sort -r | head -1)
 
 echo "Extract countries from $INPUT ..."
 
 rm -rf "${DATADIR}/.tmp"
 mkdir -p "${DATADIR}/.tmp" || exit 2
 
-WORLD_COUNTRIES="europe usa usa-caribbean usa-hawaii usa-alaska canada india new_zealand singapore"
-EUROPE_COUNTRIES="DACH austria benelux channel_islands croatia czech_republic france germany ireland italy scandinavia switzerland great_britain portugal spain canary_islands iceland monaco"
-USA_COUNTRIES="usa-northeast usa-west usa-midwest usa-south"
-
-export -f extract
-export DATADIR
-
+echo "osmium extract world"
 print_date
-
-parallel --jobs 6 --halt now,fail=1 extract ::: $INPUT ::: ${WORLD_COUNTRIES}
+osmium extract -c tk-osm/scripts/osmium-extract/planet.json "${INPUT}"
 if [ $? -ne 0 ] ; then
-  echo "parallel extracting failed"
+  echo "Extracting from planet failed"
+  cleanup 2
+fi
+
+echo "osmium extract europe 1"
+print_date
+osmium extract -c tk-osm/scripts/osmium-extract/europe1.json data/osm/.tmp/europe.osm.pbf
+if [ $? -ne 0 ] ; then
+  echo "Eextracting from europe 1 failed"
+  cleanup 2
+fi
+echo "osmium extract europe 2"
+print_date
+osmium extract -c tk-osm/scripts/osmium-extract/europe2.json data/osm/.tmp/europe.osm.pbf
+if [ $? -ne 0 ] ; then
+  echo "Eextracting from europe 2 failed"
+  cleanup 2
+fi
+echo "osmium extract europe 3"
+print_date
+osmium extract -c tk-osm/scripts/osmium-extract/europe3.json data/osm/.tmp/europe.osm.pbf
+if [ $? -ne 0 ] ; then
+  echo "Eextracting from europe 3 failed"
+  cleanup 2
+fi
+
+echo "osmium extract USA"
+print_date
+osmium extract -c tk-osm/scripts/osmium-extract/usa.json data/osm/.tmp/usa.osm.pbf
+if [ $? -ne 0 ] ; then
+  echo "Extracting from usa failed"
   exit 2
 fi
 
 print_date
 
-parallel --halt now,fail=1 extract ::: ${DATADIR}/.tmp/europe.osm.pbf ::: ${EUROPE_COUNTRIES}
-if [ $? -ne 0 ] ; then
-  echo "parallel extracting failed"
-  exit 2
-fi
-
-print_date
-
-parallel --halt now,fail=1 extract ::: ${DATADIR}/.tmp/usa.osm.pbf ::: ${USA_COUNTRIES}
-if [ $? -ne 0 ] ; then
-  echo "parallel extracting failed"
-  exit 2
-fi
-
-print_date
-
-mv ${DATADIR}/.tmp/* ${DATADIR}/
-cp -av ${INPUTDIR}/timestamp.txt ${DATADIR}/timestamp.txt
-rmdir ${DATADIR}/.tmp
+mv "${DATADIR}"/.tmp/* "${DATADIR}/"
+cp -av "${INPUTDIR}/timestamp.txt" "${DATADIR}/timestamp.txt"
+rmdir "${DATADIR}/.tmp"
